<?php
$collection = $block->getCommentCollection();
?>
<?php if (count($collection) > 0): ?>
    <div class="block review-list">
        <div class="block-title">
            <strong>Product Comments</strong>
        </div>
        <?php foreach ($collection as $item): ?>
            <div class="block-content">
                <ol class="items review-items">
                    <li class="item review-item" itemscope="" itemprop="review" itemtype="http://schema.org/Review">
                        <div class="review-content" itemprop="description"><?php echo $item->getData("body"); ?></div>
                        <div class="review-details">
                            <p class="review-author">
                                <span class="review-details-label">Commented by</span>
                                <strong class="review-details-value"
                                        itemprop="author"><?php echo $item->getData("name"); ?></strong>
                            </p>
                            <br>
                            <p class="review-date">
                                <span class="review-details-label">Posted on</span>
                                <time class="review-details-value"
                                      itemprop="datePublished"><?php echo date('m/j/Y', strtotime($item->getData("date"))); ?></time>
                            </p>
                        </div>
                    </li>
                </ol>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<form class="form" id="custom-form" action="<?=$block->getUrl('commentvisibility/index/sendComment')?>" data-mage-init='{"validation": {}}' method="post" autocomplete="off">
    <fieldset class="fieldset">
        <div class="field required">
            <label for="name" class="label"><span><?php echo __('Name') ?></span></label>
            <div class="control">
                <input type="text" name="name" id="name" value="" title="<?php echo __('Name') ?>" class="input-text" data-validate="{required:false}">
            </div>
        </div>
        <div class="field required">
            <label for="email_address" class="label"><span><?php echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email_address" value="" title="<?php echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field required">
            <label for="comment" class="label"><?php echo  __('Comment') ?></label>
            <textarea name="comment" id="comment" value="" title="<?php echo  __('Comment') ?>" class="input-text" data-validate="{required:true}"></textarea>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php  echo __('Submit') ?>"><span><?php echo __('Submit') ?></span></button>
        </div>
    </div>
</form>